### ISSUE TITLE
Can't create 2 mirrors of different size

### ISSUE THREAD

**Issue by TrueMishamol** [Norodix/GodotMirror#11]
All the mirrors are the same sizes & they copy their size based on idk - randomly chosen mirror from the scene. After that, reflections became durpy in all the mirrors except the randomly chosen one. In short:

Reflection - does resize
Mirrors - does not resize

Your Mirror addon already helped me out a lot & if it will be capable of different sizes, it would be just perfect 

The left mirror is the "chosen one" & has correct sizes. The right mirror should be wider, but it copies sizes from the left

![Mirrors](https://github.com/Norodix/GodotMirror/assets/101403719/89ad207d-0ff2-4339-865a-352fdcc5d624)

![Left](https://github.com/Norodix/GodotMirror/assets/101403719/69b12180-8f8a-40e3-9b5f-938b521375f3) 

![Right](https://github.com/Norodix/GodotMirror/assets/101403719/dfd65264-3ee6-47d4-b3b4-e6d2737a5ed5)

**Comment by Norodix** [comment]
My guess is that you copied the mirrors and they share the same viewport
resource. I can check it out when I get home, but in the meantime you can
try deleting one of them and adding it as a new node (without copy).

**Comment by TrueMishamol** [comment]
Nope, doesn't work

https://github.com/Norodix/GodotMirror/assets/101403719/273843a5-29ce-44e0-8851-6aa34e2bbf6d

I crated a new godot project for this test

Godot 4.1.1

**Comment by Norodix** [comment]
You are right, there was an issue. It was the same thing as my first guess but on the level of the resources, not on the user's level. I pushed a fix (2bc35b7a1b1e82dd6e16e28372fb8842674a9355).

If you could test it so I can be sure it works, I can push this version to the asset store.

**Comment by TrueMishamol** [comment]
Thank you! I'll test it tomorrow

**Comment by TrueMishamol** [comment]
Everything works! Even the movable once!


https://github.com/Norodix/GodotMirror/assets/101403719/d13eb9e9-3b67-4de3-9874-afcb9492cde5


But now I found another 2 issues ahah

1. Mirrors reveal the true nature of my bad topology in 3d models. I don't want them to uncover all my secrets!
2. In the editor after launching Godot project at first time, all my mirrors appear with duplicates

https://github.com/Norodix/GodotMirror/assets/101403719/9cc46beb-c4fd-40cb-9af0-b97494dc8c60

To fix it, I simply reopen .tscn. 

The problem appears even in new projects. When I created a brand new project for testing new update & then reopen it, you see what happens:

https://github.com/Norodix/GodotMirror/assets/101403719/48119002-c976-451d-b877-6d8ddd1a5fba

It also affect all new Mirrors created before reopening scene

Should I create new Issues for this 2 bugs?

**Comment by Norodix** [comment]
I suspect the duplicates are this fix's fault. Unless you can replicate it with a previous version dont open a new issue, just keep this one open.

Regarding the 1st issue about the topology. To me it seems a bit like either transparency sorting issue or maybe LOD issue. Can you try disabling autolod and try again? It could be an issue with using multiple cameras, that only 1 decides the level of detail. But these are just guesses.

**Comment by TrueMishamol** [comment]
Yeah! It totally was the auto-LOD
Thank you

![image](https://github.com/Norodix/GodotMirror/assets/101403719/b40b04c3-ec1d-43e9-9b96-5f10547cb3c3)

**Comment by Norodix** [comment]
My guess is maybe godot takes the active camera into account when selecting the level of detail. Maybe that is why it happens, but I'm happy it works now.

I can't really reproduce your other issue, so I cant test it. Try moving the 2 new lines that duplicate the mesh to ready from enter_tree, or try setting mesh to null before those 2 lines. I'm on linux, if you are on windows its possible that this is a race condition or some other edge case. If you find a way that is more reliable than it is now, I'm happy to modify.

**Comment by TrueMishamol** [comment]
Hello, once again :)

Ok, for me editor-side problem with duplicated mirrors is not crucial, so I leave it for later.

But I found, that after exporting all mirrors appears to be black
As always, I additionally test all in an empty project:

Before export / After export
![image](https://github.com/Norodix/GodotMirror/assets/101403719/7b4f926d-2d82-40b3-b1c1-a7ee64f59bd9)

**Comment by TrueMishamol** [comment]
No errors in console

![image](https://github.com/Norodix/GodotMirror/assets/101403719/829b4d68-dcb8-4882-a324-f71850d162ac)

Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
Vulkan API 1.2.142 - Forward+ - Using Vulkan Device #0: NVIDIA - GeForce GTX 1650

**Comment by Norodix** [comment]
Mine looks even more fun. Its weird, I have not seen this issue yet. I will look into it when I have time!

![image](https://github.com/Norodix/GodotMirror/assets/36245389/c0c33b74-b7cc-48c6-8a6f-40082286a11d)

**Comment by Norodix** [comment]
I think I got it. I needed to set the update mode of the subviewport to either parent visible or always. Please test it: https://github.com/Norodix/GodotMirror/commit/ab051bd2b8fb6376d892c1a84e3e8653db9edf52

**Comment by TrueMishamol** [comment]
Hooray! It works!
