### ISSUE TITLE
Remove duplicate frustum code in `Mirror`

### ISSUE THREAD

**Issue by Firepal** [Norodix/GodotMirror#3]
The `Mirror.gd` and `MirrorCamera.gd` scripts share copied code with minimal changes.

To reduce code duplication, we can simply use `MirrorCamera` inside of `MirrorContainer` and just set that up in the `Mirror.gd` script.

**Comment by Norodix** [comment]
I just realized that `MirrorCamera.gd` is dead code that I forgot to delete. No node uses it. Thanks for noticing, I will delete it soon.

**Comment by Norodix** [comment]
Fixed in 6f2590687c34217776b9e2beca90cbb1861bbbe8

**Comment by Firepal** [comment]
Eh, couldn't find a reason for it to exist either. :]
