### ISSUE TITLE
Mirror does not work if nested inside a node within a ViewportContainer/Viewport

### ISSUE THREAD

**Issue by elvisish** [Norodix/GodotMirror#6]
If the scene structure is:
Main
----Mirror

it works fine, but breaks if the structure is:
Main
----Level
--------Mirror

Still trying to figure out how to fix this, it also seems to create duplicate viewport textures and cameras.

**Comment by elvisish** [comment]
Actually, I think it breaks if it's a child of a viewport (as I'm using) for some reason. I move my entire level node into a sub-viewport and this seems to break the mirror and how it creates it's container node.

**Comment by Norodix** [comment]
What exactly do you mean by "it breaks"? Does it not render correctly? Does it throw an error that halts the game? 

I see no reason so far that this should cause any issues.

**Comment by elvisish** [comment]
> What exactly do you mean by "it breaks"? Does it not render correctly? Does it throw an error that halts the game? 
> 
> 
> 
> I see no reason so far that this should cause any issues.

Me neither, looking at the code. It seems to create two MirrorInstance nodes if it's a child of a viewport and the two try to overlay each other and z-fight without showing anything.

**Comment by Norodix** [comment]
I tested it by adding a mirror as a child of a new viewport in the demo scene. I didnt see anything unexpected. Can you be a bit more specific? A minimal reproduction project would help. Preferably with the demo scene.

**Comment by elvisish** [comment]
It was creating two versions of MirrorInstance, possibly because when I move my level into a ViewportContainer it was calling enter_tree twice(?), but I fixed it with:
```swift
var do_once := false


func _enter_tree():
	if do_once:
		return
	var node = preload("MirrorContainer.tscn").instance()
	add_child(node)
	do_once = true
```
