### ISSUE TITLE
AssetLib Download gives a 404 error

### ISSUE THREAD

**Issue by EhoNo1** [Norodix/GodotMirror#9]
**Describe the bug**
Attempting to download the project through the asset library gives a 404.

**To Reproduce**
In Godot 4, Open the AssetLib
Search for "Godot Mirror" and/or browse to this project
Attempt to download through the editor
Editor should report a 404 error.

**Expected behavior**
The add-on should either successfully download or (if this is intended) inform the user about manual installation in the asset library description.

**Screenshots**
![image](https://github.com/Norodix/GodotMirror/assets/37421719/76bb4e65-79ff-4fc7-abe0-7f9280ddf97d)

**Godot version**
v4.0.2.stable.official [7a0977ce2]

**Platform**
Windows 11

**Additional context**
I tried downloading two other random addons (trackball camera and radial menu) and they succeeded. I don't know enough about the godot asset library to know how to fix this or provide suggestions. (Or even if this issue has anything to do with the project. Apologies in advanced if it's entirely out of your control!)

**Comment by Norodix** [comment]
I think they changed something regarding the asset library and the computed url changed because of that. 
It is overall because there is a branch for godot 4 and 3 too. This should be fixed now, though it might take some time for the asset lib to accept the change. (sorry for the late reply)
